### ISSUE TITLE
net _builder package is none

### ISSUE THREAD

**Issue by sunshine-lh** [AlexMV12/PyCrCNN#6]
In the list, I can't find the net_builder package.

**Comment by AlexMV12** [comment]
Hi Sunshine,

You are right, we are in the middle of a refactor and I have to update the documentation.
If you want to give a look at the current version of the tool, I would give a look at the notebook in the HE-ML folder (HE-ML.ipynb).
Please let me know if you have any problems!

Have a nice day,
AlexMV12

**Comment by sunshine-lh** [comment]
Hi AlexMV12,

Thank you for your reply！

Have a nice day,
Sunshine
