### ISSUE TITLE
Encryption parameters are not set correctly

### ISSUE THREAD

**Issue by nrakurniawan** [AlexMV12/PyCrCNN#7]
Hi, I try to run your example code of HE-ML_CKKS.ipynb

encryption_parameters = {
    'm': n,                      # For CKKS, n/2 values can be encoded in a single ciphertext
    'scale': 2**scale_power,                 # Each multiplication grows the final scale
    'qi': [34]+ [scale_power]*n_mults +[34]  # One intermdiate for each multiplication
}

HE_Client = CKKSPyfhel(**encryption_parameters)
HE_Client.generate_keys()
HE_Client.generate_relin_keys()

got this errors:
----------------
Exception ignored in: 'Pyfhel.Pyfhel.Pyfhel.keyGen'
Traceback (most recent call last):
  File "../pycrcnn/he/HE.py", line 221, in generate_keys
ValueError: encryption parameters are not set correctly

I have tried to change the parameters setting: n_mults, n, scale_power, it did not works.
How to solve this problem?

I'm using Pyfhel version 3.3.0

Thanks before

**Comment by AlexMV12** [comment]
Hi nrakurniawan,

We are sorry for these bugs, we have interesting plans for PyCrCNN but it still needs some work.
However, I've fixed the problem you faced. Now the notebook should work. 

Please note that you need to install Pyfhel with the `SEAL_THROW_ON_TRANSPARENT_CIPHERTEXT` flag set to off. You can read about this here: https://github.com/ibarrond/Pyfhel/issues/124

It's not difficult, though. You just need to clone Pyfhel in local (as shown in their readme file), change the flag in pyproject.toml, and install it.

**Comment by nrakurniawan** [comment]
Hi AlexMV12,
Thank you for your reply and explanation.

I tried to install the Pyfhel library with `SEAL_THROW_ON_TRANSPARENT_CIPHERTEXT` flag set to OFF.

I got the following error, do you know how to solve it?
Thanks before.

```
Processing /home/hendra/Pyfhel-master
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy==1.21
  Using cached numpy-1.21.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Building wheels for collected packages: Pyfhel
  Building wheel for Pyfhel (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for Pyfhel (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_py
      copying Pyfhel/__init__.py -> build/lib.linux-x86_64-3.8/Pyfhel
      running build_clib
      building 'SEAL' cmake-based library
      CMake Error: The source directory "/home/hendra/Pyfhel-master/Pyfhel/backend/SEAL" does not appear to contain CMakeLists.txt.
      Specify --help for usage, or press the help button on the CMake GUI.
      Error: could not load cache
      building 'Afhel' shared library
      gcc -pthread -B /home/hendra/anaconda3/envs/pyfhel/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/hendra/Pyfhel-master/Pyfhel/Afhel -I/home/hendra/Pyfhel-master/build/temp.linux-x86_64-3.8/Pyfhel/SEAL/native/src -I/home/hendra/Pyfhel-master/Pyfhel/backend/SEAL/native/src -I/home/hendra/Pyfhel-master/Pyfhel/backend/SEAL/thirdparty/msgsl-src/include -c /home/hendra/Pyfhel-master/Pyfhel/Afhel/Afseal.cpp -o build/temp.linux-x86_64-3.8/home/hendra/Pyfhel-master/Pyfhel/Afhel/Afseal.o -std=c++17 -O3 -fopenmp
      cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      In file included from /home/hendra/Pyfhel-master/Pyfhel/Afhel/Afseal.cpp:32:0:
      /home/hendra/Pyfhel-master/Pyfhel/Afhel/Afseal.h:47:10: fatal error: seal/dynarray.h: No such file or directory
       #include "seal/dynarray.h"
                ^~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pyfhel
Failed to build Pyfhel
ERROR: Could not build wheels for Pyfhel, which is required to install pyproject.toml-based projects
```

**Comment by AlexMV12** [comment]
When you cloned Pyfhel, did you do it with `git clone --recursive https://github.com/ibarrond/Pyfhel.git` ?

**Comment by AlexMV12** [comment]
Mhm, honestly, I don't know how to solve it. You should look at the Pyfhel repo to see if someone had this problem.
Maybe you may try to use Google Colab to run the notebook.

**Comment by nrakurniawan** [comment]
Thank you for your suggestion.
I will post it here if I have solved it.

**Comment by nrakurniawan** [comment]
I have solved this issue by updating and upgrading apt-get and also updating build-essential.
Thanks for your help.

**Comment by AlexMV12** [comment]
You're welcome! Let me know if you need anything else.
