### ISSUE TITLE
No requirements.txt

### ISSUE THREAD

**Issue by stealthBanana** [AlexMV12/PyCrCNN#8]
Hi, 
I had a problem where I had to install the tenseal package since it is imported in pycrcnn.he.HE, this package was not listed in the "external libraries used" section of the README. Wouldn't it be easier if here was a requirements file in the repo.

Cheers

**Comment by AlexMV12** [comment]
Hello stealthBanana,

You are totally right. I added a `requirements.txt` file and also wrote a bit more on the requirements (for instance, you will see that for Pyfhel you have to do a little modification to make it work correctly).

Let me know if there is anything else.

Thanks!
Alessandro
